version: "2"
services:
    web:
      image: ubuntu:16.04
      container_name: ubuntu16
      ports:
        - "8085:80"
      command: "apt update && apt install -y binutils"
      volumes:
        - ./how-linux-work:/code