version: "2"

services:
  web:
    build: ./
    # image: ubuntu:16.04
    container_name: ubuntu-16
    ports:
      - "8085:80"
    # command: "apt update && apt install binutils build-essential sysstat -y"
    command: "/bin/bash"
    volumes:
      - "./how-linux-work:/code"
    tty: true  